# Generated by Django 4.0 on 2022-01-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafedra_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='file',
            field=models.FileField(default=1, upload_to='uploads/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
